# Generated by Django 2.0.3 on 2018-03-11 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_votes', models.IntegerField(default=0)),
                ('comment_pub_date', models.DateTimeField(verbose_name='com pub date')),
            ],
        ),
        migrations.CreateModel(
            name='Etymology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etymology_text', models.TextField()),
                ('classification', models.CharField(max_length=150)),
                ('etymology_votes', models.IntegerField(default=0)),
                ('etymology_pub_date', models.DateTimeField(verbose_name='Ety date published')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=150)),
                ('term_type', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='etymology',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progety.Term'),
        ),
        migrations.AddField(
            model_name='comment',
            name='etymology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progety.Etymology'),
        ),
    ]
