# Generated by Django 2.0.3 on 2018-03-13 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='term_pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Term Pub Date'),
            preserve_default=False,
        ),
    ]
